CLASS zcl_lab_30_org_germany_ag DEFINITION
  PUBLIC
  INHERITING FROM zcl_lab_29_organization_ag
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS get_location REDEFINITION.
  PROTECTED SECTION.
ENDCLASS.



CLASS ZCL_LAB_30_ORG_GERMANY_AG IMPLEMENTATION.


  METHOD get_location.
    rv_location = 'Germany'.
  ENDMETHOD.
ENDCLASS.
