CLASS zcl_lab_39_budget_ag DEFINITION
  ABSTRACT
  PUBLIC.

  PUBLIC SECTION.
    METHODS get_budget ABSTRACT RETURNING VALUE(rv_text) TYPE string.
    PROTECTED SECTION.
ENDCLASS.


CLASS zcl_lab_39_budget_ag IMPLEMENTATION.
ENDCLASS.

