CLASS zcl_lab_12_linux_ag DEFINITION INHERITING FROM zcl_lab_11_system_ag
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_12_linux_ag IMPLEMENTATION.
ENDCLASS.

