CLASS zcl_lab_23_company_ag DEFINITION
  PUBLIC
  CREATE PUBLIC
  GLOBAL FRIENDS zcl_lab_24_partner_ag.

  PRIVATE SECTION.
    DATA capital TYPE string VALUE '1000000'.

ENDCLASS.



CLASS ZCL_LAB_23_COMPANY_AG IMPLEMENTATION.
ENDCLASS.
