CLASS zcl_lab_19_lion_ag DEFINITION INHERITING FROM zcl_lab_18_animal_ag
  PUBLIC
  CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS ZCL_LAB_19_LION_AG IMPLEMENTATION.


  METHOD walk.
    rv_walk = 'The lion walks'.
  ENDMETHOD.
ENDCLASS.
